dist: bionic
language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install -g typescript
  - npm install
script:
  - npm run build && npm run doc
  - travis_wait 30 npm run coveralls
git:
  depth: 1