dist: bionic
language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
install:
  - npm install -g typescript
  - npm install
script:
  - npm run build && npm run doc && npm run test
git:
  depth: 1