/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Auxiliary information about a ballot other than the selections made by the voter.
 */
export interface BallotInformation {
  /**
   * Information about the device that encrypted the ballot
   */
  device_info: string;
  /**
   * The date the ballot was encrypted.
   */
  date: string;
  /**
   * The time the ballot was encrypted.
   */
  time: string;
  /**
   * The tracker code generated for this ballot.
   */
  tracker: string;
  [k: string]: any;
}
