/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BallotStyle {
  districts: string[];
  id: string;
  partyId?: string;
  precincts: string[];
  [k: string]: any;
}
export interface BMDConfig {
  requireActivation?: boolean;
  showHelpPage?: boolean;
  showSettingsPage?: boolean;
  [k: string]: any;
}
export interface CandidateContest {
  allowWriteIns: boolean;
  candidates: Candidate[];
  districtId: string;
  id: string;
  partyId?: string;
  seats: number;
  section: string;
  title: string;
  type: "candidate";
  [k: string]: any;
}
export interface Candidate {
  id: string;
  isWriteIn?: boolean;
  name: string;
  partyId?: string;
  [k: string]: any;
}
export interface YesNoContest {
  description: string;
  districtId: string;
  id: string;
  partyId?: string;
  section: string;
  shortTitle: string;
  title: string;
  type: "yesno";
  [k: string]: any;
}
export interface County {
  id: string;
  name: string;
  [k: string]: any;
}
export interface District {
  id: string;
  name: string;
  [k: string]: any;
}
export interface Party {
  abbrev: string;
  id: string;
  name: string;
  [k: string]: any;
}
export interface Precinct {
  id: string;
  name: string;
  [k: string]: any;
}
