/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A unsigned integer, which can be given as a string or a number, not including the number zero.
 */
export type BigNaturalNumber = string | number;
