/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The safe prime modulus `p`
 */
export type BigUint = string | number;
/**
 * The generator `g` of the multiplicative subgroup `Z^*_q`, where `p = 2q + 1`.
 */
export type BigNaturalNumber = string | number;

/**
 * All the parameters necessary to form the election.
 */
export interface ElectionParameters {
  /**
   * The date on which the election takes place.
   */
  date: string;
  /**
   * The location where the election takes place
   */
  location: string;
  /**
   * The configuration file used in the election.
   */
  ballotCodingFile?: {
    ballotStyles: {
      districts: string[];
      id: string;
      partyId?: string;
      precincts: string[];
      [k: string]: any;
    }[];
    bmdConfig?: {
      requireActivation?: boolean;
      showHelpPage?: boolean;
      showSettingsPage?: boolean;
      [k: string]: any;
    };
    contests: (
      | {
          allowWriteIns: boolean;
          candidates: {
            id: string;
            isWriteIn?: boolean;
            name: string;
            partyId?: string;
            [k: string]: any;
          }[];
          districtId: string;
          id: string;
          partyId?: string;
          seats: number;
          section: string;
          title: string;
          type: "candidate";
          [k: string]: any;
        }
      | {
          description: string;
          districtId: string;
          id: string;
          partyId?: string;
          section: string;
          shortTitle: string;
          title: string;
          type: "yesno";
          [k: string]: any;
        })[];
    county: {
      id: string;
      name: string;
      [k: string]: any;
    };
    date: string;
    districts: {
      id: string;
      name: string;
      [k: string]: any;
    }[];
    parties: {
      abbrev: string;
      id: string;
      name: string;
      [k: string]: any;
    }[];
    precincts: {
      id: string;
      name: string;
      [k: string]: any;
    }[];
    seal?: string;
    sealURL?: string;
    state: string;
    title: string;
    [k: string]: any;
  };
  prime: BigUint;
  generator: BigNaturalNumber;
  /**
   * The number of election trustees `n`.
   */
  num_trustees: number;
  /**
   * The threshold `k` of trustees required to complete verification.
   */
  threshold: number;
  [k: string]: any;
}
