name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm update
    - run: npm install -g typescript
    - run: npm install
    - run: tsc --noEmit
    - run: node node_modules/eslint/bin/eslint.js '{src,tests}/**/*.{js,ts,tsx}' --quiet
    - run: npm run build --if-present
    - run: npm run doc
    - run: node node_modules/jest/bin/jest.js --coverage

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # required, use a github secret for that
        fail_ci_if_error: true              # optional (default=false)
