name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn global add typescript
    - run: yarn
    - run: yarn lint:check
    - run: yarn build
    - run: yarn doc
    - run: yarn coverage

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # required, use a github secret for that
        fail_ci_if_error: true              # optional (default=false)
